name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - uses: snok/install-poetry@v1
        with:
          virtualenvs-create: false
      - name: Install dependencies
        run: poetry install --no-interaction --no-ansi --with dev
      - name: Run linter
        run: poetry run pre-commit run --all-files --show-diff-on-failure --color always
      - name: Run tests
        run: |
          mkdir -p reports
          poetry run pytest -q --junitxml=reports/junit.xml | tee reports/pytest.txt
      - name: Upload test report
        uses: actions/upload-artifact@v3
        with:
          name: test-report
          path: reports/
